chore: add discord example
callstack/byorg-ai pull request #25
Opened 2024-12-05 11:19 UTC by Q1w1N

### Summary
new example for discord integration

### Test plan
tested with discord

2024-12-05 11:58 UTC, mdjastrzebski commented on .changeset/cuddly-mangos-train.md
> +'discord-example': patch
[nit] implementing example actually accounts as a minor ;-)
```suggestion
'discord-example': minor
```

2024-12-05 11:59 UTC, mdjastrzebski commented on examples/discord/package.json
>      "@callstack/byorg-core": "0.4.2",
can you replace all 0.4.2 references with workspace? There was a bug if you released it with changeset, but now we do release it with `pnpm` so we can use workspace

2024-12-05 11:59 UTC, mdjastrzebski commented on packages/discord/package.json
> +  "version": "0.4.3",
Leave version updating to changset

2024-12-05 12:00 UTC, mdjastrzebski commented on packages/discord/src/index.ts
> +export type DiscordClient = Client & ClientStart;
Add code comment documenting this hack

2024-12-05 12:00 UTC, mdjastrzebski commented on packages/discord/src/index.ts
> +  client.start = () => {
Why are we adding methods to existing discord object?

2024-12-05 12:01 UTC, mdjastrzebski commented on packages/discord/src/index.ts
> +  client.start = () => {
I do not see any code in this PR actually calling this method. Is it needed?

2024-12-05 12:02 UTC, mdjastrzebski requested changes
I have some questions in the comments

2024-12-05 12:13 UTC, Q1w1N commented on packages/discord/src/index.ts
> +  client.start = () => {
No added

2024-12-07 07:16 UTC, mdjastrzebski commented on .changeset/cuddly-mangos-train.md
> +changed passing bot token variable and discord login
```suggestion
discord: changed passing bot token variable and discord login
```

2024-12-07 07:17 UTC, mdjastrzebski approved these changes

2024-12-07 07:19 UTC, mdjastrzebski approved these changes
Approved!

2024-12-07 07:51 UTC, merged